name: .NET 8 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore NameSorter.sln

      - name: Build solution
        run: dotnet build NameSorter.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test NameSorter.sln --configuration Release --no-build --verbosity normal